#!/usr/bin/env node
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Render Build Script: Set Backend URL in environment.production.ts
 * 
 * Reads BACKEND_URL from environment variable and writes it to
 * the Angular production environment file before build.
 * 
 * Usage: node scripts/render-set-env.mjs
 * Required env var: BACKEND_URL=https://your-backend.onrender.com
 */

const backendUrl = process.env.BACKEND_URL;

if (!backendUrl) {
  console.error('❌ ERROR: BACKEND_URL environment variable is not set');
  console.error('   Set it in Render dashboard: Environment Variables > BACKEND_URL');
  process.exit(1);
}

if (!backendUrl.startsWith('https://') && !backendUrl.startsWith('http://localhost')) {
  console.error('❌ ERROR: BACKEND_URL must start with https:// (got:', backendUrl, ')');
  console.error('   Use the full Render URL: https://your-backend.onrender.com');
  process.exit(1);
}

const envFilePath = resolve(__dirname, '../src/environments/environment.production.ts');

const content = `// Auto-generated by scripts/render-set-env.mjs during Render build
// DO NOT manually edit - run the script to regenerate
export const environment = {
  production: true,
  apiBaseUrl: '${backendUrl}',
};
`;

try {
  writeFileSync(envFilePath, content, 'utf8');
  console.log('✅ Generated environment.production.ts');
  console.log('   API Base URL:', backendUrl);
} catch (err) {
  console.error('❌ Failed to write environment.production.ts:', err);
  process.exit(1);
}
