// This file is auto-generated by scripts/render-set-env.mjs during Render build
// DO NOT manually edit in production - it will be overwritten
// For local production builds, set BACKEND_URL env var before building
export const environment = {
  production: true,
  apiBaseUrl: '', // Will be replaced during Render build
};
